# Generated by Django 6.0 on 2025-12-11 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=20, unique=True)),
                ('note', models.TextField()),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('ai_status', models.CharField(default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=10)),
                ('note', models.TextField()),
                ('original_name', models.CharField(max_length=255)),
                ('supabase_path', models.CharField(max_length=512)),
                ('supabase_url', models.TextField()),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size', models.PositiveBigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('ai_status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='storage_app.filegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='filegroup',
            constraint=models.UniqueConstraint(fields=('user', 'group_id'), name='unique_user_group'),
        ),
        migrations.AlterUniqueTogether(
            name='uploadedfile',
            unique_together={('user', 'file_hash')},
        ),
    ]
