# Generated by Django 6.0 on 2025-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filegroup',
            name='ai_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
