# Generated by Django 6.0 on 2025-12-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_uploadedfile_ai_status_uploadedfile_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
