# Generated by Django 6.0 on 2025-12-10 23:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_alter_uploadedfile_options_uploadedfile_sub_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadedfile',
            unique_together={('user', 'file_hash')},
        ),
    ]
