# Generated by Django 6.0 on 2025-12-11 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_alter_uploadedfile_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filegroup',
            constraint=models.UniqueConstraint(fields=('user', 'group_id'), name='unique_user_group'),
        ),
    ]
